In [2]:
import pandas as pd
data = {
    'Nome': ['Alice', 'Bob', 'Charlie', 'David', 'Elena', 'Federico', 'Giorgia'],
    'Dipartimento': ['HR', 'IT', 'IT', 'Marketing', 'Sales', 'IT', 'Sales'],
    'Stipendio': [31000, 45000, 52000, 38000, 42000, 48000, 33000],
    'Anni_Esperienza': [2, 5, 10, 4, 7, 6, 3]
}

df = pd.DataFrame(data)
df

       Nome Dipartimento  Stipendio  Anni_Esperienza
0     Alice           HR      31000                2
1       Bob           IT      45000                5
2   Charlie           IT      52000               10
3     David    Marketing      38000                4
4     Elena        Sales      42000                7
5  Federico           IT      48000                6
6   Giorgia        Sales      33000                3

In [ ]:
# Questa è una VIEW: non modifica il dataframe originale
# ma ne visualizza solo una parte
df['Nome']

0       Alice
1         Bob
2     Charlie
3       David
4       Elena
5    Federico
6     Giorgia
Name: Nome, dtype: object

In [4]:
df

       Nome Dipartimento  Stipendio  Anni_Esperienza
0     Alice           HR      31000                2
1       Bob           IT      45000                5
2   Charlie           IT      52000               10
3     David    Marketing      38000                4
4     Elena        Sales      42000                7
5  Federico           IT      48000                6
6   Giorgia        Sales      33000                3

In [ ]:
# view
df.sort_values(by="Anni_Esperienza", ascending=True)

# creo una copia modificata
df_sorted = df.sort_values(by="Anni_Esperienza", ascending=True)

In [17]:
media = df["Stipendio"].mean()
condizione = df['Stipendio'] < media
print(df[condizione][['Nome', "Dipartimento"]])

      Nome Dipartimento
0    Alice           HR
3    David    Marketing
6  Giorgia        Sales

In [13]:
print(df[["Nome", "Stipendio"]])

       Nome  Stipendio
0     Alice      31000
1       Bob      45000
2   Charlie      52000
3     David      38000
4     Elena      42000
5  Federico      48000
6   Giorgia      33000

In [14]:
# view --> temporanea, serve solo per "vedere" ma non modifica nulla

# copia modificata --> crea una modifica
def return_selection(df):
    return df[["Nome", "Stipendio"]]

print(return_selection(df))

       Nome  Stipendio
0     Alice      31000
1       Bob      45000
2   Charlie      52000
3     David      38000
4     Elena      42000
5  Federico      48000
6   Giorgia      33000